### ISSUE TITLE
TODO: Register Vimes in the General registry

### ISSUE THREAD

**Issue by DilumAluthge** [MikeInnes/Vimes.jl#10]
I am opening this issue to keep track of what needs to be done before we can register Vimes in the General registry.

Currently, the blocking issues are:
- [ ] https://github.com/julia-vscode/CSTParser.jl/pull/80.

Until https://github.com/julia-vscode/CSTParser.jl/pull/80 is merged, perhaps we can keep the patched copy of `CSTParser` inside this repository? Similar to the way that Pkg [keeps a copy of TOML inside the Pkg repository](https://github.com/JuliaLang/Pkg.jl/tree/master/ext/TOML).

This would allow us to register Vimes without having to wait for https://github.com/julia-vscode/CSTParser.jl/pull/80 to be merged.

**Comment by DilumAluthge** [comment]
Alternatively, you could register [your fork](https://github.com/MikeInnes/CSTParser.jl) of CSTParser in the General registry with a different name, such as `CSTParser2` or `CSTParserX`.

**Comment by MikeInnes** [comment]
Copying the code is easy but does have the issue that we then have to maintain it, and it's harder to just rebase our patches over any changes to CSTParser proper. So a fork might be easier maintenance-wise.

**Comment by DilumAluthge** [comment]
This is done: https://github.com/JuliaRegistries/General/tree/master/V/Vimes
