### ISSUE TITLE
Suggestion: Set up Bors on this repository

### ISSUE THREAD

**Issue by DilumAluthge** [MikeInnes/Vimes.jl#12]
https://github.com/bors-ng/bors-ng

Will need to set up Travis first (https://github.com/MikeInnes/Vimes.jl/issues/11).

**Comment by MikeInnes** [comment]
I'm not wildly against, though it seems like there's not a huge benefit to bors here. I'm not really expecting to have a lot of semantic conflicts (but could be proven wrong of course).

**Comment by DilumAluthge** [comment]
I'm going to close this issue as stale.
